defaults: &defaults
  app_id: <%= ENV['FOURSQUARE_APP_ID'] %>
  app_secret: <%= ENV['FOURSQUARE_APP_SECRET'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twitter_access_key: <%= ENV['TWITTER_ACCESS_KEY'] %>
  twitter_access_secret: <%= ENV['TWITTER_ACCESS_SECRET'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
